# Generated by Django 3.2.3 on 2021-09-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creator_Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('art', 'ART'), ('design', 'DESIGN'), ('fashion', 'FASHION'), ('food', 'FOOD'), ('games', 'GAME'), ('technology', 'TECHNOLOGY'), ('photography', 'PHOTOGRAPHY')], default='technology', max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='creator_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
