# Generated by Django 3.1.13 on 2021-09-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_auto_20210917_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator_basic',
            name='category',
            field=models.CharField(choices=[('1', 'Art'), ('2', 'Technology'), ('Testfor3', 'Fasion'), ('4', 'Food'), ('5', 'Photography'), ('6', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='creator_basic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creator_fund',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
