# Generated by Django 3.1.13 on 2021-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_auto_20210918_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator_basic',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
