# Generated by Django 3.2.7 on 2021-09-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_auto_20210918_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator_basic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creator_basic',
            name='image',
            field=models.ImageField(upload_to='media/static/img'),
        ),
        migrations.AlterField(
            model_name='creator_fund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
