# Generated by Django 3.1.13 on 2021-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_auto_20210918_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator_basic',
            name='image',
            field=models.ImageField(upload_to='media/static/img'),
        ),
    ]
