# Generated by Django 3.2.3 on 2021-09-19 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_auto_20210919_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='creator_fund',
        ),
        migrations.AddField(
            model_name='creator_basic',
            name='FundingGoal',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='creator_basic',
            name='TargetLaunchDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='creator_basic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
