# Generated by Django 3.1.13 on 2021-09-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_auto_20210919_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator_basic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
