# Generated by Django 3.2.7 on 2021-09-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_auto_20210920_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator_basic',
            name='reciepient',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creator_basic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
