# Generated by Django 3.2.3 on 2021-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0012_auto_20210920_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator_basic',
            name='pledgeAmount',
            field=models.IntegerField(default='0'),
        ),
    ]
