# Generated by Django 3.2.7 on 2021-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0013_creator_basic_pledgeamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator_basic',
            name='Author',
            field=models.CharField(default='exit', max_length=25),
            preserve_default=False,
        ),
    ]
