# Generated by Django 3.2.7 on 2021-09-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile_Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=25)),
                ('Phone', models.IntegerField(default='0')),
                ('Adress', models.CharField(max_length=25)),
                ('Funded', models.IntegerField(default='0')),
                ('Projects', models.CharField(max_length=100)),
            ],
        ),
    ]
