# Generated by Django 3.2.3 on 2021-09-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_basic',
            old_name='Adress',
            new_name='Address',
        ),
    ]
