# Generated by Django 3.2.3 on 2021-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investor_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('zipNo', models.IntegerField()),
                ('cardName', models.TextField()),
                ('cardNum', models.IntegerField()),
            ],
        ),
    ]
