# Generated by Django 3.2.3 on 2021-09-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_auto_20210917_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor_fund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
