# Generated by Django 3.2.7 on 2021-09-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_auto_20210918_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor_fund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
