# Generated by Django 3.1.13 on 2021-09-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0007_alter_investor_fund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor_fund',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
