# Generated by Django 3.2.3 on 2021-09-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0009_alter_investor_fund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor_fund',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='investor_fund',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='investor_fund',
            name='cardName',
        ),
        migrations.RemoveField(
            model_name='investor_fund',
            name='cardNum',
        ),
        migrations.RemoveField(
            model_name='investor_fund',
            name='email',
        ),
        migrations.RemoveField(
            model_name='investor_fund',
            name='zipNo',
        ),
        migrations.AddField(
            model_name='investor_fund',
            name='pledgeAmount',
            field=models.IntegerField(default='0'),
        ),
    ]
