# Generated by Django 3.2.3 on 2021-09-21 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0010_auto_20210921_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor_fund',
            name='name',
        ),
        migrations.AddField(
            model_name='investor_fund',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investor_fund',
            name='projectid',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='investor_fund',
            name='updated_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investor_fund',
            name='userid',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='investor_fund',
            name='username',
            field=models.CharField(default='', max_length=25),
        ),
    ]
