# Generated by Django 3.2.3 on 2021-09-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0011_auto_20210921_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor_fund',
            name='projectid',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='investor_fund',
            name='userid',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='investor_fund',
            name='username',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
