# Generated by Django 3.2.3 on 2021-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0012_auto_20210921_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor_fund',
            name='transactiondata',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
